### User Registration
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "email": "example@example.com",
  "fullName": "user123",
  "password": "password123",
  "phoneNumber": "0526372223"
}

### User Login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "password123"
}

### Get Authenticated User Profile
GET http://localhost:3001/api/auth/check
Authorization: Bearer {auth_token}

### Get All Posts
GET http://localhost:3001/api/post
Authorization: Bearer {auth_token}

### Create a New Post
POST http://localhost:3001/api/post
Authorization: Bearer {auth_token}
Content-Type: application/json

{
  "body": "This is a new post",
  "imageUrl": "http://example.com/image.jpg"
}

### Edit a Post
PUT http://localhost:3001/api/post/{postId}
Authorization: Bearer {auth_token}
Content-Type: application/json

{
  "body": "Updated post content",
  "imageUrl": "http://example.com/new-image.jpg"
}

### Delete a Post
DELETE http://localhost:3001/api/post/{postId}
Authorization: Bearer {auth_token}

### Get User's Posts
GET http://localhost:3001/api/post/user
Authorization: Bearer {auth_token}

### Get Favorite Posts
GET http://localhost:3001/api/post/favorites
Authorization: Bearer {auth_token}

### Like a Post
POST http://localhost:3001/api/post/{postId}/like
Authorization: Bearer {auth_token}

### Create a Comment on a Post
POST http://localhost:3001/api/comment/{postId}
Authorization: Bearer {auth_token}
Content-Type: application/json

{
  "body": "This is a comment"
}

### Edit a Comment
PUT http://localhost:3001/api/comment/{commentId}
Authorization: Bearer {auth_token}
Content-Type: application/json

{
  "body": "Updated comment text"
}

### Delete a Comment
DELETE http://localhost:3001/api/comment/{commentId}
Authorization: Bearer {auth_token}


###
POST https://graph.facebook.com/v22.0/570249219514789/messages
Authorization: Bearer EAAaJWZCxpt3QBO7qGc3QQcZA9GDL5GwXUCIZBEUnc6QSDwoKYgFRPUTkAWHJfcZCplOX1MAZCBrHL9qONj7HHMGJSB4ZAhLowNx202IFqW6gdwXqMGpUBt51qDJHKwYYQlaWftQ83Qt660WHkyZBBZCXZANbZCCUbv8EoHtECgaDytrZAjwRUPcNioJMatmPOEWGu0jHVGe2sDWUJ09p0OpKOoB0sLxxzofYjPFszIZD
Content-Type: application/json

{
  "messaging_product": "whatsapp",
  "to": "972526757973",
  "type": "text",
  "text": {
    "body": "You have been added to a safe circle. Please download the app to connect with your loved ones."
  }
}
