

export enum BluetoothState {
    DISCONNECTED='DISCONNECTED',
    SCANNING='SCANNING',
    SCAN_TIMEOUT='SCAN_TIMEOUT',
    CONNECTING='CONNECTING',
    CONNECTED='CONNECTED',
    DISCONNECTING='DISCONNECTING',
    TRANSFER_INCOMPLETE='TRANSFER_INCOMPLETE',
}