

export enum BluetoothError {
    BLUETOOTH_DISABLED='BLUETOOTH_DISABLED',
    PERMISSION_DENIED='PERMISSION_DENIED',
    SECURITY_ERROR='SECURITY_ERROR',
    SCAN_FAILED='SCAN_FAILED',
    CONNECTION_FAILED='CONNECTION_FAILED',
    SERVICE_DISCOVERY_FAILED='SERVICE_DISCOVERY_FAILED',
    CHARACTERISTIC_NOT_FOUND='CHARACTERISTIC_NOT_FOUND',
    DISCONNECT_FAILED='DISCONNECT_FAILED',
    COMMAND_FAILED='COMMAND_FAILED',
    DATA_ERROR='DATA_ERROR',
}